apiVersion: apps/v1
kind: Deployment
metadata:
  name: cema-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cema-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: cema-ui
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: cema-ui
        image: cemaregistry.azurecr.io/cema/cema-ui:$VERSION
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: VUE_APP_API_URL
          value: $BE_URL
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: cema-ui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: cema-ui
